name:                servant-job
version:             0.2.0.0
github:              np/servant-job
license:             BSD3
author:              "Nicolas Pouillard"
maintainer:          "nicolas.pouillard@gmail.com"
copyright:           "2018 Nicolas Pouillard"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Job API in Haskell Servant
category:            Web

description: Please see the README on Github at <https://github.com/np/servant-job#readme>

dependencies:
- aeson
- async
- base >= 4.7 && < 5
- bytestring
- containers
- deepseq
- http-api-data
- http-client
- kan-extensions
- lens
- mtl
- SHA
- scientific
- servant >= 0.16
- servant-flatten
- servant-client-core >= 0.16
- servant-client >= 0.16
- servant-server >= 0.16
- servant-swagger >= 1.1.5
- split
- swagger2
- text
- time
- unordered-containers

library:
  source-dirs: src
  exposed-modules:
  - Servant.Job.Types
  - Servant.Job.Async
  - Servant.Job.Core
  - Servant.Job.Utils
  - Servant.Job.Client
  - Servant.Job.Server

executables:
  servant-job-calc-example:
    main:                calc.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-job
    - wai
    - warp
  servant-job-scrapy-example:
    main:                scrapy-orch.hs
    source-dirs:         example
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-job
    - warp
    - http-client-tls

# executables:
#   servant-job-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - servant-job

# tests:
#   servant-job-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - servant-job
